### ISSUE TITLE
could not import services and models

### ISSUE THREAD

**Issue by vgtechs** [bluesnap/bluesnap-android-int#7]
I just tried to add Bluesnap Anroid SDK into my app, added compile 'com.bluesnap:bluesnap-android: 2.0.2' into dependecies section of gradle file, but after sync, it was only views inported, and model and services was not.
So I getting not recognized by Android Studio following strings (as example): 
import com.bluesnap.androidapi.models.BillingInfo;
import com.bluesnap.androidapi.models.SdkResult;
import com.bluesnap.androidapi.models.ShippingInfo;
import com.bluesnap.androidapi.services.AndroidUtil;
import com.bluesnap.androidapi.services.BluesnapServiceCallback;

those string all red color and not recognized by Android Studio.
P.S. I'm using Android Studio 3.1.3 (Windows), gradle 4.4 and  minSdkVersion 23, targetSdkVersion 27

Thanks

**Comment by emailsubjekt** [comment]
Dude, don't add compile, add implementation, also did the problem go away or not. I am a little worried about these guys not answering on this. What if I have a problem and no one answers here? I don't want to use a library no one maintains.

**Comment by snpori** [comment]
Hi. 
The project is maintained and updated regularly.
This issue is quite old and refers to a an old version.
If you have any further issues you can also contact the support on bluesnap.com
